### ISSUE TITLE
Using relative pathnames in the test

### ISSUE THREAD

**Issue by Yehouda** [GrammaTech/elf#1]
The tes use relative pathnames, which rely on the crrent directory being the test direct, which not really a reasonabel assumption. It should use **asdf:system-relative-pathname** to specify the full pathname. Suggested changes below (i don;t do pull requests at the moment), all in test/elf-test.lisp:

;;;;----------------------------------------------------
;;; Add a function 

(defun elf-test-relative-path (rel-path-string)
    (asdf/system:system-relative-pathname "elf/test" (concatenate 'string "test/" rel-path-string)))

;;;;----------------------------------
;;;;;;   Replace exiting form:  use elf-test-relative-path 

(defixture hello-elf
  (:setup
   (setf *tmp-file* (elf-test-relative-path "hello.tmp"))
   (when (probe-file *tmp-file*) (delete-file *tmp-file*))
   (setf *elf* (read-elf (case *test-class*
                           (:32-bit (elf-test-relative-path "hello32"))
                           (:64-bit (elf-test-relative-path "hello64"))))))
  (:teardown
   (when (probe-file *tmp-file*)
     (delete-file *tmp-file*))))

;;;; --------------------------------------------
;;;;; Replace exiting form:  use elf-test-relative-path 

(deftest test-objdump-parse-empty-instructions ()
  (let ((lines (with-open-file (in (elf-test-relative-path "main.txt"))
                               (loop for line = (read-line in nil :eof)
                                  until (eq line :eof)
                                  collect line))))
    (is (elf::equal-it '(0) (second (nth 12 (parse-addresses lines)))))))

;;;; -----------------------------------------------
;;; BTW: any idea how to  indent the code  properly here?

**Comment by eschulte** [comment]
Thanks for these fixes, they've all been applied.  If you surround code blocks with three consequtive "`" on a line that will cause it to be indented as code.  Read about "markdown" to learn more.

Thanks!
